/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* Microchip Technology Inc. e suas subsidiárias. 
 * Você pode usar este software e quaisquer derivados 
 * exclusivamente com produtos Microchip.

 * ESTE SOFTWARE É FORNECIDO PELA MICROCHIP "TAL COMO ESTÁ". 
 * NENHUMA GARANTIA, EXPRESSA, IMPLÍCITA OU ESTATUTÁRIA, 
 * SE APLICA A ESTE SOFTWARE, INCLUINDO QUALQUER GARANTIA IMPLÍCITA 
 * DE NÃO INFRACÇÃO, COMERCIALIZAÇÃO E ADEQUAÇÃO A UM PROPÓSITO ESPECÍFICO OU 
 * SUA INTERAÇÃO COM PRODUTOS MICROCHIP, 
 * COMBINAÇÃO COM QUALQUER OUTRO PRODUTO OU UTILIZAÇÃO EM QUALQUER APLICAÇÃO.
 * 
 * EM NENHUM CASO A MICROCHIP SERÁ RESPONSÁVEL POR QUALQUER PERDA INDIRETO,
 * ESPECIAL, PUNITIVA, INCIDENTAL OU CONSEQUENCIAL,DANOS, CUSTO OU 
 * DESPESAS DE QUALQUER TIPO DE RELAÇÃO COM O SOFTWARE, NO ENTANTO, CAUSADO,
 * MESMO QUE MICROCHIP TENHA SIDO AVISADA DA POSSIBILIDADE OU 
 * DOS DANOS PREVISÍVEIS.
 * NA MÁXIMA EXTENSÃO PERMITIDA POR LEI,A RESPONSABILIDADE TOTAL DA MICROCHIP 
 * EM TODAS AS REIVINDICAÇÕES DE QUALQUER FORMA RELATIVA A ESTE SOFTWARE 
 * NÃO EXCEDERÁ A QUANTIDADE DE TAXAS, SE HOUVER, 
 * QUE VOCÊ PAGOU DIRETAMENTE À MICROCHIP POR ESTE SOFTWARE.
 * 
 * A MICROCHIP FORNECE ESTE SOFTWARE CONDICIONALMENTE COM SUA ACEITAÇÃO 
 * DESTES TERMOS.
 */

/* 
 * File:    config.h
 * Author:  Curta Eletrônica
 * Comments:Arquivo de configuração do microcontrolador via diretivas de 
 *          compilação e definições (defines).
 * Revision history: 
 *      1:  Criação do arquivo de configuração.
 *      2:  Tradução dos termos de aceitação de uso do MPLABX da Microchip;
 *          Comentário nas diretivas e definições (defines).
 */

#ifndef CONFIG_H
#define CONFIG_H

#pragma config FOSC  = INTRC_NOCLKOUT   // Fonte de clock: oscilador interno
#pragma config WDTE  = OFF              // Desabilita WatchDog Timer 
#pragma config MCLRE = OFF              // Desab. Master Clear via pino
#pragma config LVP   = OFF              // Desab. gravação em baixa tensão

#define _XTAL_FREQ     4000000          // Freq. clock interno: 4MHz(padrão)

#endif
